# Generated by Django 4.1.5 on 2023-01-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_craeted_producto_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaprod',
            name='craeted',
        ),
        migrations.RemoveField(
            model_name='categoriaprod',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='craeted',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='updated',
        ),
    ]
